framework:
  assets:
    # json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    packages:
      website:
        json_manifest_path: "%kernel.project_dir%/public/build/website/manifest.json"
      admin:
        json_manifest_path: "%kernel.project_dir%/public/build/admin/manifest.json"
