# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  allowed_methods_listener: true
  view:
    mime_types:
      json:
        [
          application/json,
          application/json;version=1.0,
          application/json;version=1.1,
        ]
    view_response_listener: force
    formats:
      json: true
  format_listener:
    rules:
      - {
          path: ^/api,
          priorities: [json],
          fallback_format: json,
          prefer_extension: true,
        }
      - {
          path: ^/,
          priorities: [text/html, "*/*"],
          fallback_format: html,
          prefer_extension: true,
        }
