app_index:
  path: /
  controller: App\Controller\WebsiteController::index

cms_index:
  path: /admin/{page}/{action}/{var1}/{var2}
  controller: App\Controller\AdminController::index
  defaults:
    page: null
    action: null
    var1: null
    var2: null

api_login:
  path: /api/login_check
  methods: [POST]
